var $=window.$=function(a){if(this.$)return new $(a);void 0===a&&(a=[document]);a==document&&(a=[document.documentElement]);this.elem="string"!=typeof a?$.isArray(a)?a:[a]:"<"==a[0]?[document.createElement(a.substr(1,a.length-2))]:document.querySelectorAll(a)};
$.plugin=$.prototype={n:function(a){return 0<=a&&a<this.elem.length?$(this.elem[a]):null},len:function(){return this.elem.length},index:function(){for(var a=0,b=this.elem[0];null!=(b=b.previousElementSibling);)++a;return a},find:function(a){var b=[];$.every.call(this,function(){$.find(this,a,b)});return $(b)},every:function(a){$.every.call(this,a);return this},event:function(a,b,d){var c=a.split(" ");for(a=0;a<c.length;a++)d=d||!1,$.every.call(this,function(){for(var a=0;a<c.length;a++){"mousewheel"==c[a]&&(c[a]="onwheel"in document?"wheel":"onmousewheel"in document?"mousewheel":"DOMMouseScroll");if(window.addEventListener===undefined){var m=d?function(a){a=a||window.event;b.call(this,a);window.event.cancelBubble=!0}:function(a){a=a||window.event;b.call(this,a)};this.attachEvent("on"+c[a],m)}else d?m=function(a){a=a||window.event;b.call(this,a);a.stopPropagation()}:
(m="mouseleave"==c[a]&&void 0===document.onmouseleave||"mouseenter"==c[a]&&void 0===document.onmouseenter?function(a){a=a||window.event;for(var c=a.relatedTarget||a.toElement;c&&c!==this;)c=c.parentNode;c!=this&&b.call(this,a)}:function(a){a=a||window.event;b.call(this,a)},"mouseleave"==c[a]&&void 0===document.onmouseleave&&(c[a]="mouseout"),"mouseenter"==c[a]&&void 0===document.onmouseenter&&(c[a]="mouseover")),this.addEventListener(c[a],m,!1)}});return this},submit:function(a){this.event("submit",a);return this},hashchange:function(a){this.event("hashchange",a);return this},click:function(a){this.event("click",
a);return this},dblclick:function(a){this.event("dblclick",a);return this},mousedown:function(a){this.event("mousedown",a);return this},mouseup:function(a){this.event("mouseup",a);return this},mouseover:function(a){this.event("mouseover",a);return this},mouseout:function(a){this.event("mouseout",a);return this},mousemove:function(a){this.event("mousemove",a);return this},mouseleave:function(a){this.event("mouseleave",a);return this},mouseenter:function(a){this.event("mouseenter",a);return this},mousewheel:function(a){this.event("mousewheel",
a);return this},scroll:function(a){this.event("scroll",a);return this},resize:function(a){this.event("resize",a);return this},change:function(a){this.event("change",a);return this},cut:function(a){this.event("cut",a);return this},copy:function(a){this.event("copy",a);return this},paste:function(a){this.event("paste",a);return this},keypress:function(a){this.event("keypress",a);return this},keydown:function(a){this.event("keydown",a);return this},keyup:function(a){this.event("keyup",a);return this},
focus:function(a){void 0===a?this.elem[0].focus():this.event("focus",a);return this},blur:function(a){void 0===a?this.elem[0].blur():this.event("blur",a);return this},next:function(){var a,b=[];$.every.call(this,function(){var c;a=this;for(c=0;1>c;c++)for(;null!=a.nextSibling;)if("[object Text]"==a.nextSibling)a=a.nextSibling;else{0==c?b.push(a.nextSibling):a=a.nextSibling;break}});return $(b)},prev:function(){var a,b=[];$.every.call(this,function(){var c;a=this;for(c=0;1>c;c++)for(;null!=a.previousSibling;)if("[object Text]"==
a.previousSibling)a=a.previousSibling;else{0==c?b.push(a.previousSibling):a=a.previousSibling;break}});return $(b)},parent:function(a){var b=[];$.every.call(this,function(){if(void 0===a)b.push(this.parentNode);else{for(var c=this,d=0;d<a;d++)if(null!=c.parentNode)c=c.parentNode;else break;b.push(c)}});return $(b)},matches:function(a){var b=document.documentElement;b=b.matchesSelector||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;for(var c=0;c<this.elem.length;c++)if(1==
b.call(this.elem[c],a))return!0;return!1},position:function(a){var b=[],c=document.body,d=document.documentElement,f=window.pageYOffset||d.scrollTop||c.scrollTop,g=window.pageXOffset||d.scrollLeft||c.scrollLeft,h=d.clientTop||c.clientTop||0,k=d.clientLeft||c.clientLeft||0;if($.isArray(a)&&"*"==a)return $.every.call(this,function(){e=this.getBoundingClientRect();b.push({top:Math.round(e.top+f-h),left:Math.round(e.left+g-k)})}),b;if(void 0===a){var e=this.elem[0].getBoundingClientRect();return{top:Math.round(e.top+
f-h),left:Math.round(e.left+g-k)}}},offset:function(a){var b=[];if($.isArray(a)&&"*"==a)return $.every.call(this,function(){c=this.getBoundingClientRect();b.push({top:Math.round(c.top),left:Math.round(c.left)})}),b;var c=this.elem[0].getBoundingClientRect();return{top:Math.round(c.top),left:Math.round(c.left)}},scrollTop:function(a){if(void 0===a)return this.elem[0].scrollTop;$.every.call(this,function(){this.scrollTop=a});return this},scrollLeft:function(a){if(void 0===a)return this.elem[0].scrollLeft;
$.every.call(this,function(){this.scrollLeft=a});return this},height:function(a){if($.isArray(a)&&"*"==a){var b=[];$.every.call(this,function(){b.push(this.offsetHeight)});return b}if(void 0===a)return this.elem[0].offsetHeight;$.every.call(this,function(){this.style.height=$.isNumber(a)?a+"px":a});return this},innerHeight:function(a){if($.isArray(a)&&"*"==a){var b=[];$.every.call(this,function(){b.push(this.clientHeight-parseInt($(this).css("paddingTop"))-parseInt($(this).css("paddingBottom")))});
return b}return this.elem[0].clientHeight-parseInt(this.css("paddingTop"))-parseInt(this.css("paddingBottom"))},clientHeight:function(a){if($.isArray(a)&&"*"==a){var b=[];$.every.call(this,function(){b.push(this.clientHeight)});return b}return this.elem[0].clientHeight},outerHeight:function(a){if($.isArray(a)&&"*"==a){var b=[];$.every.call(this,function(){b.push(this.offsetHeight+parseInt($(this).css("marginTop"))+parseInt($(this).css("marginBottom")))});return b}return this.elem[0].offsetHeight+
parseInt(this.css("marginTop"))+parseInt(this.css("marginBottom"))},scrollHeight:function(a){if($.isArray(a)&&"*"==a){var b=[];$.every.call(this,function(){b.push(this.scrollHeight)});return b}return this.elem[0].scrollHeight},append:function(a){var b=!0;$.isObject(a)&&$.every.call(this,function(c){if(b)for(c=0;c<a.elem.length;c++)if(this==a.elem[c]){b=!1;break}});b&&$.every.call(this,function(b){if($.isObject(a))for(b=0;b<a.elem.length;b++)this.insertAdjacentElement("beforeEnd",a.elem[b].cloneNode(!0));
else("string"===$.type(a)||$.isNumber(a))&&this.insertAdjacentHTML("beforeEnd",a)});return this},attach:function(a){var b=!0;$.isObject(a)&&$.every.call(this,function(c){if(b)for(c=0;c<a.elem.length;c++)if(this==a.elem[c]){b=!1;break}});b&&$.every.call(this,function(b){if($.isObject(a))for(b=0;b<a.elem.length;b++)this.insertAdjacentElement("afterBegin",a.elem[b].cloneNode(!0));else("string"===$.type(a)||$.isNumber(a))&&this.insertAdjacentHTML("afterBegin",a)});return this},before:function(a){var b=
!0;$.isObject(a)&&$.every.call(this,function(c){if(b)for(c=0;c<a.elem.length;c++)if(this==a.elem[c]){b=!1;break}});b&&$.every.call(this,function(b){if($.isObject(a))for(b=0;b<a.elem.length;b++)this.insertAdjacentElement("beforeBegin",a.elem[b].cloneNode(!0));else("string"===$.type(a)||$.isNumber(a))&&this.insertAdjacentHTML("beforeBegin",a)});return this},after:function(a){var b=!0;$.isObject(a)&&$.every.call(this,function(c){if(b)for(c=0;c<a.elem.length;c++)if(this==a.elem[c]){b=!1;break}});b&&$.every.call(this,
function(b){if($.isObject(a))for(b=0;b<a.elem.length;b++)this.insertAdjacentElement("afterEnd",a.elem[b].cloneNode(!0));else("string"===$.type(a)||$.isNumber(a))&&this.insertAdjacentHTML("afterEnd",a)});return this},html:function(a){if(void 0===a)return this.elem[0].innerHTML;$.every.call(this,function(){this.innerHTML=$.isFunc(a)?a.call(this):a});return this},css:function(a,b){if(void 0!==b)return $.every.call(this,function(){this.style[a]="string"===$.type(b)||$.isNumber(b)?b:b.call(this)}),this;
if("string"===$.type(a))return window.getComputedStyle?getComputedStyle(this.elem[0],null)[a]:this.elem[0].currentStyle[a];if($.isObject(a)){for(b in a)$.every.call(this,function(){this.style[b]="string"===$.type(a[b])||$.isNumber(a[b])?a[b]:a[b].call(this)});return this}},attr:function(a,b){if(void 0===b){if("string"===$.type(a))return this.elem[0].getAttribute(a);if($.isObject(a))return $.every.call(this,function(){for(var b in a)this.setAttribute(b,$.isFunc(a[b])?a[b].call(this):a[b])}),this}else return $.every.call(this,
function(){this.setAttribute(a,$.isFunc(b)?b.call(this):b)}),this},removeAttr:function(){var a=arguments;$.every.call(this,function(){for(var b=0;b<a.length;b++)this.removeAttribute(a[b])});return this},addClass:function(a){$.every.call(this,function(){!1===$.checkClass.call(this,"string"===$.type(a)?a:a.call(this))&&("string"===$.type(a)?this.className=""==this.className?a:this.className+(" "+a):$.isFunc(a)&&(this.className=""==this.className?a.call(this):this.className+(" "+a.call(this))))});return this},
removeClass:function(){var a=arguments;$.every.call(this,function(){for(var b=0;b<a.length;b++)$.isFunc(a[b])&&(a[b]=a[b].call(this)),0<this.className.indexOf(" "+a[b]+" ")?this.className=this.className.replace(" "+a[b]+" "," "):0==this.className.indexOf(a[b]+" ")?this.className=this.className.replace(a[b]+" ",""):0==this.className.indexOf(a[b])&&this.className==a[b]?this.className=this.className.replace(a[b],""):this.className.indexOf(" "+a[b])==this.className.length-a[b].length-1&&(this.className=
this.className.replace(" "+a[b],""))});return this},hasClass:function(a){return $.checkClass.call(this.elem[0],a)}};$.find=function(a,b,c){for(var d=0;d<a.children.length;d++)$(a.children[d]).matches(b)&&c.push(a.children[d]),$.find(a.children[d],b,c);return c};$.every=function(a){if($.isFunc(a))for(var b=0;b<this.elem.length;b++)a.call(this.elem[b],b)};
$.ready=function(a){function b(){c||(c=!0,a())}var c=!1;if(document.addEventListener)document.addEventListener("DOMContentLoaded",function(){b()},!1);else if(document.attachEvent){if(document.documentElement.doScroll&&window==window.top){var d=function(){if(!c&&document.body)try{document.documentElement.doScroll("left"),b()}catch(f){setTimeout(d,0)}};d()}document.attachEvent("onloadedstatechange",function(){"complete"===document.loadedState&&b()})}window.addEventListener?window.addEventListener("load",
b,!1):window.attachEvent&&window.attachEvent("onload",b)};$.isFunc=function(a){return void 0===a?!1:"function"===$.type(a)};$.type=function(a){return null===a?"null":typeof a};$.isNumber=function(a){return"number"==$.type(a)&&Infinity!==a};$.checkClass=function(a){$.isFunc(a)&&(a=a.call(this));return 0<this.className.indexOf(" "+a+" ")?!0:0==this.className.indexOf(a+" ")?!0:0==this.className.indexOf(a)&&this.className==a?!0:this.className.indexOf(" "+a)==this.className.length-a.length-1?!0:!1};
$.isArray=function(a){return void 0===a?!1:a.push?!0:!1};