$.ready(function(){function a(a){a=document.body.scrollTop||document.documentElement.scrollTop;for(var b=0;b<h;b++)-1!=g[b].className.indexOf("opened")&&$(g[b]).removeClass("opened");for(b=h-1;0<=b;b--){var c=e.n(b).position().top;if(a>=c){-1==g[b].className.indexOf("active")&&(g[b].className+=" active");for(c=0;c<h;c++)b!=c&&-1!=g[c].className.indexOf("active")&&(g[c].className=g[c].className.replace(/[\s]*active/,""));break}}-150<a-l.position().top+l.height()&&(l.hasClass("visible")||l.addClass("visible"));
terminal_percent=(a-l.position().top+l.height())/l.height();terminal_percent=Math.min(1,Math.max(0,terminal_percent));b=Math.round(222*terminal_percent);u.html().length!=Math.round(222*terminal_percent)&&u.html('from keras.models import Sequential\nfrom keras.layers import Dense\nimport numpy\n\nnumpy.random.seed(7)\n\ndataset = numpy.loadtxt("hackathon_data.csv", delimiter=",")\n\nX = dataset[:,0:8]\nY = dataset[:,8]\n\nmodel = Sequential()'.substr(0,b));-150<a-k.position().top+k.height()?k.hasClass("visible")||
k.addClass("visible"):k.hasClass("visible")&&k.removeClass("visible");lecture_percent=(a-k.position().top+k.height())/k.height();lecture_percent=Math.min(1,Math.max(0,lecture_percent));v.css("opacity",lecture_percent);v.css("transform","translate("+-10*(1-lecture_percent)+"%, "+12*(1-lecture_percent)+"%) scale("+(.5+lecture_percent/2)+")");light_percent=(a-n.position().top+n.height())/n.height();light_percent=Math.min(1,Math.max(0,light_percent));w.css("opacity",light_percent);tetris_percent=(a-p.position().top+
p.height())/p.height();1.05<tetris_percent?m.hasClass("breaked")||m.addClass("breaked"):(m.hasClass("breaked")&&m.removeClass("breaked"),tetris_percent=Math.min(1,Math.max(0,tetris_percent)),tetris_percent=Math.floor(85*tetris_percent),tetris_percent=tetris_percent-tetris_percent%10+5*Math.round(tetris_percent%10/5),x.css("top",tetris_percent+"%"));brains_percent=(a-q.position().top+q.height())/q.height();brains_percent=Math.min(1,Math.max(0,brains_percent));y.attr("stroke-dashoffset","-"+450*brains_percent);
bag_percent=(a-r.position().top+r.height())/r.height()+.5;bag_percent=Math.min(1,Math.max(0,bag_percent));z.css("transform","rotateX(-"+50*bag_percent+"deg)")}function d(b){window.matchMedia("only screen and (max-device-width: 480px), only screen and (max-device-height: 480px), only screen and (max-width: 900px)").matches&&c.removeClass("visible");var a=this.getAttribute("href");-1!=document.querySelector(this.getAttribute("href")).className.indexOf("subpage")?scroll_to(document.querySelector(this.getAttribute("href")).offsetTop+
document.querySelector(this.getAttribute("href")).parentNode.parentNode.parentNode.offsetTop,300):scroll_to(document.querySelector(this.getAttribute("href")).offsetTop,300);history.pushState?history.pushState(null,null,a):setTimeout(function(){location.hash=a},300);t=a;b.preventDefault()}animate_wave();$(".page#main");$(".page-container>.page-header-menu");var e=$(".page, .subpage:not(#tetrix2016-info)"),h=e.len(),c=$(".sidebar-nav");$(".sidebar-item#link-main");var g=$(".sidebar-nav > li").elem,
b=$("#gallery-big-photo").elem[0],f=$("#gallery-big-video"),l=$(".slide-action#terminal"),k=$(".slide-action#lecture"),v=$("#lecture-sound"),n=$(".slide-action#startup"),w=$("#startup-light"),p=$(".slide-action#tetris"),x=$("#tetris-item"),m=$("#tetris-screen"),q=$(".slide-action#brains"),y=$("#brains-path"),r=$(".slide-action#vacancies"),z=$("#vacancies-bag"),u=$("#terminal-text"),t=location.hash;$(".sidebar-nav a").click(d);$("#gallery-all").mousewheel(function(a){window.matchMedia("(orientation: portrait)").matches||
(-120==a.wheelDelta?scroll_to(this.scrollTop+150,125,this):120==a.wheelDelta?scroll_to(this.scrollTop-150,125,this):this.scrollTop-=Math.round(a.wheelDelta/4));a.preventDefault();return!1});$(".gallery-pic").click(function(a){if(-1==this.className.indexOf("video")){if(-1!=b.className.indexOf("hidden")||-1!=b.className.indexOf("gallery-video"))b.className="";f.hasClass("hidden")||(f.addClass("hidden"),f.attr("src",""));b.style.background="url("+this.getAttribute("href")+") center center no-repeat, url("+
this.childNodes[0].getAttribute("src")+") center center no-repeat"}else-1==b.className.indexOf("hidden")&&(b.className="hidden"),f.hasClass("hidden")&&f.removeClass("hidden"),f.attr("src",this.getAttribute("href"));a.preventDefault();return!1});$(b).click(function(a){-1!=b.className.indexOf("gallery-video")&&(-1==b.className.indexOf("hidden")&&(b.className="hidden"),f.hasClass("hidden")&&f.removeClass("hidden"),f.attr("src","https://drive.google.com/file/d/0B5-nfqzQWvTYVTFvaHU5bVJiVjg/preview?autoplay=1"))});
$(window).resize(a);$(window).scroll(a);$("#tetrix2016-partners .subpage-details").click(d);$(".sidebar-icon").click(function(a){c.hasClass("visible")||c.addClass("visible");history.pushState?history.pushState(null,null,"#menu"):location.hash="#menu";t="#menu";a.preventDefault()});window.onhashchange=function(a){"#menu"==t&&c.hasClass("visible")&&c.removeClass("visible")}});
function animate_wave(){function a(){for(var f=0;f<g.length;f++){switch(f){case 2:b=[92,93];break;case 4:b=[25,30];break;case 5:b=[97,101];break;case 6:b=[53,60];break;case 7:b=[88,95]}if(0!=b.length){var k=Math.abs(b[e]-b[+!e]);tmp_val=quartic(d,4.091,-8.6272,4.86691,.65351,.01307);tmp_val*=k*(2*e-1);tmp_val+=b[+!e];g[f]=tmp_val;c[f]=g[f]}b=[]}h.attr("d",c.join(" "));d+=.002;1<d&&(d=0,e=+!e);window.requestAnimationFrame(a)}for(var d=0,e=0,h=$("#main-wave #float-path"),c=h.attr("d").split(" "),g=
[],b=[],f=0;f<c.length;f++)"M"==c[f]||"C"==c[f]||"L"==c[f]?g.push(c[f]):g.push(+c[f]);window.requestAnimationFrame(a)}function approx(a,d,e){return d<a?a-Math.abs(d-a)*e:a+Math.abs(d-a)*e}function cubic_bezier(a,d,e,h,c){return Math.pow(1-a,3)*d+3*a*Math.pow(1-a,2)*e+3*Math.pow(a,2)*(1-a)*h+Math.pow(a,3)*c}function quartic(a,d,e,h,c,g){return d*Math.pow(a,4)+e*Math.pow(a,3)+h*Math.pow(a,2)+c*a+g}
function scroll_to(a,d,e){function h(){var a=Date.now();if(a<=c)var d=0;else a>=g?d=1:(d=(a-c)/(g-c),d=d*d*(3-2*d));d=Math.round(b+f*d);e.scrollTop=d;a>=g||e.scrollTop===l&&e.scrollTop!==d||(l=e.scrollTop,void 0!==window.requestAnimationFrame?window.requestAnimationFrame(h):setTimeout(h,0))}e=void 0===e?document.documentElement:e;a=Math.round(a);d=Math.round(d);var c=Date.now(),g=c+d,b=e.scrollTop,f=a-b,l=e.scrollTop;h()};